# Generated by Django 5.1 on 2025-04-23 08:19

from django.db import migrations

def insert_initial_categories(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    categories = [
        {'name': '漫画', 'english_name': 'comic', 'slug': 'comic', 'description': '漫画'},
        {'name': '小説', 'english_name': 'novel', 'slug': 'novel', 'description': '小説'},
        {'name': '雑誌', 'english_name': 'magazine', 'slug': 'magazine', 'description': '雑誌'},
        {'name': '専門書', 'english_name': 'special', 'slug': 'special', 'description': '専門書'},
        {'name': '実用書', 'english_name': 'practical', 'slug': 'practical', 'description': '実用書'},
    ]
    
    for category_data in categories:
        Category.objects.create(**category_data)

def remove_initial_categories(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    Category.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_initial_categories, remove_initial_categories),
    ]
